# Generated by Django 4.2.3 on 2023-08-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bio',
            new_name='body',
        ),
    ]
